# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'swiftui-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swiftui-demo
  pod 'MinCloud', :git => 'https://github.com/ifanrx/hydrogen-ios-sdk.git', :branch => 'fix_bug'
end
