# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Daily' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Daily
  pod 'MinCloud', :git => 'https://github.com/ifanrx/hydrogen-ios-sdk.git'

end
